kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
metadata:
  name: mongodb-circleci-demo
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
  zone: us-east-1a
  iopsPerGB: "10"
#  encrypted: "true"